### PR TITLE
Add arm inverse kinematics

### PR DESCRIPTION
**Pull request by mdepp**
Adds a moveit config to control the arm using the ros_control arm controller. I initially made this configuration using the moveit config tool, but then manually edited it, so there may be problems with running the tool again.

For some reason, the actual states the arm is willing to move to are extremely limited.

### CODE REVIEW

**Comment by mdepp** [comment]
I think the limited goal states are because the rviz gui is also specifying ending orientation. It has a wide range of motion if I just go to random valid states.

**Comment by rpshukla** [comment]
I tried it out and it seems to work!

One question though: do we need all the launch files in case_moveit_config?

**Comment by mdepp** [comment]
Definitely not. They're automatically generated though so I wanted to change them as little as possible.

**Comment by rpshukla** [comment]
> Definitely not. They're automatically generated though so I wanted to change them as little as possible.

Ok fair enough

**Pull request merged**
